version: '3'
services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-application
    restart: always
    ports:
      - "8082:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - php-app-network

networks:
  php-app-network:
    driver: bridge
